;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua--shift-control-c-prefix
	mouse-yank-primary
	))

(setq mc/cmds-to-run-once
      '(
	TeX-command-master
	cua--prefix-repeat-handler
	))
