;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	cua--shift-control-c-prefix
	cua-copy-region
	electric-verilog-tab
	mouse-yank-primary
	org-end-of-line
	org-self-insert-command
	))

(setq mc/cmds-to-run-once
      '(
	TeX-command-master
	cua--prefix-repeat-handler
	))
